
services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - mysql:/val/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_TCP_PORT: 3307

    ports:
      - "3307:3307"
    expose:
      - "3307"

volumes:
  mysql: